"""statements table

Revision ID: 1fbc13506e1f
Revises: 
Create Date: 2019-01-10 15:11:20.458971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbc13506e1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement')
    # ### end Alembic commands ###
